MODULES+=	markdown-filter

MODULE_SUMMARY_markdown_filter=	Dynamic module markdown filter for nginx

MODULE_CONTRIB_DEPS_markdown-filter=	ngx_markdown_filter_module

include $(foreach dep,$(MODULE_CONTRIB_DEPS_markdown-filter),$(CONTRIB)/src/$(dep)/version)

MODULE_NAME_markdown_filter=	ngx_markdown_filter_module

MODULE_VERSION_markdown_filter=	0.1.7
MODULE_RELEASE_markdown_filter=	1

MODULE_VERSION_PREFIX_markdown_filter=$(BASE_VERSION)+

MODULE_SOURCES_markdown_filter=	ngx_markdown_filter_module-$(NGX_MARKDOWN_FILTER_MODULE_VERSION).tar.gz
MODULE_CONFARGS_markdown_filter=	--add-dynamic-module=$(MODSRC_PREFIX)$(MODULE_NAME_markdown_filter)
MODULE_BUILD_DEPENDS_markdown_filter=cmark-dev

.deps-module-markdown-filter:
	cd $(CONTRIB) && make .sum-ngx_markdown_filter_module
	touch $@

define MODULE_POST_markdown_filter
cat <<BANNER
----------------------------------------------------------------------

The $(MODULE_SUMMARY_markdown_filter) for $(MODULE_SUMMARY_PREFIX) has been installed.
To enable this module, add the following line to /etc/nginx/nginx.conf
and reload nginx:

    load_module modules/ngx_http_markdown_filter_module.so;

----------------------------------------------------------------------
BANNER
endef
export MODULE_POST_markdown_filter
