MODULES+=	include-server

MODULE_SUMMARY_include_server=	enable support to include_server directive in nginx.conf

MODULE_CONTRIB_DEPS_include-server=	ngx_http_include_server_module

include $(foreach dep,$(MODULE_CONTRIB_DEPS_include-server),$(CONTRIB)/src/$(dep)/version)

MODULE_NAME_include_server=	ngx_http_include_server_module

MODULE_VERSION_include_server=	0.01
MODULE_RELEASE_include_server=	1

MODULE_VERSION_PREFIX_include_server=$(BASE_VERSION)+

MODULE_SOURCES_include_server=	ngx_http_include_server_module-$(NGX_HTTP_INCLUDE_SERVER_MODULE_GITHASH).tar.gz
MODULE_CONFARGS_include_server=	--add-dynamic-module=$(MODSRC_PREFIX)$(MODULE_NAME_include_server)

.deps-module-include-server:
	cd $(CONTRIB) && make .sum-ngx_http_include_server_module
	touch $@

define MODULE_POST_include_server
cat <<BANNER
----------------------------------------------------------------------

The $(MODULE_SUMMARY_include_server) for $(MODULE_SUMMARY_PREFIX) has been installed.
To enable this module, add the following line to /etc/nginx/nginx.conf
and reload nginx:

    load_module modules/ngx_http_include_server_module.so;

----------------------------------------------------------------------
BANNER
endef
export MODULE_POST_include_server
