MODULES+=	error-page-inherit

MODULE_SUMMARY_error_page_inherit=	enable support to error_page_inherit directive in nginx.conf

MODULE_NAME_error_page_inherit=	ngx_http_error_page_inherit_module

MODULE_VERSION_error_page_inherit=	0.01
MODULE_RELEASE_error_page_inherit=	1

MODULE_VERSION_PREFIX_error_page_inherit=$(BASE_VERSION)+

MODULE_SOURCES_error_page_inherit=	https://github.com/RekGRpth/$(MODULE_NAME_error_page_inherit).git
MODULE_CONFARGS_error_page_inherit=	--add-dynamic-module=$(MODULE_NAME_error_page_inherit)

define MODULE_POST_error_page_inherit
cat <<BANNER
----------------------------------------------------------------------

The $(MODULE_SUMMARY_error_page_inherit) for $(MODULE_SUMMARY_PREFIX) has been installed.
To enable this module, add the following line to /etc/nginx/nginx.conf
and reload nginx:

    load_module modules/ngx_http_error_page_inherit_module.so;

----------------------------------------------------------------------
BANNER
endef
export MODULE_POST_error_page_inherit
