47c47
< download_pkg = mkdir -p $(TARBALLS) && $(call download,$(1))
---
> download_pkg = $(call download,$(CONTRIB_NGINX)/$(2)/$(lastword $(subst /, ,$(@))))
49,50c49,50
< download_pkg = mkdir -p $(TARBALLS) && { $(call download,$(1)) || \
< 	( $(call download,$(CONTRIB_NGINX)/$(2)/$(lastword $(subst /, ,$(@)))) && echo "Downloaded from CONTRIB_NGINX fallback" ); }
---
> download_pkg = $(call download,$(CONTRIB_NGINX)/$(2)/$(lastword $(subst /, ,$(@)))) || \
> 	( $(call download,$(1)) && echo "Please upload $(lastword $(subst /, ,$(@))) to $(CONTRIB_NGINX)" && echo "mkdir -p contrib/$(2); cd contrib/$(2) && curl -f -L -- \"$(1)\" > \"$(lastword $(subst /, ,$(@)))\" && cd ../.." )
