MODULES+=	error-page-inherit

MODULE_SUMMARY_error_page_inherit=	enable support to error_page_inherit derective in nginx.conf.

MODULE_CONTRIB_DEPS_error-page-inherit=	nginx-error-page-inherit

include $(foreach dep,$(MODULE_CONTRIB_DEPS_error-page-inherit),$(CONTRIB)/src/$(dep)/version)

MODULE_VERSION_error_page_inherit=	0.01
MODULE_RELEASE_error_page_inherit=	1

MODULE_VERSION_PREFIX_error_page_inherit=$(MODULE_TARGET_PREFIX)

MODULE_PACKAGE_VENDOR_error_page_inherit=		Georgy Shelkovy [RekGRpth]

MODULE_PACKAGE_URL_error_page_inherit=		https://github.com/RekGRpth

MODULE_NAME_error_page_inherit=	ngx_http_error_page_inherit_module

MODULE_PACKAGE_LICENSE_error_page_inherit=	MIT

MODULE_SOURCES_error_page_inherit=	ngx_http_error_page_inherit_module-$(NGINX_ERROR_PAGE_INHERIT_VERSION).tar.gz

MODULE_CONFARGS_error_page_inherit=	--add-dynamic-module=$(MODSRC_PREFIX)$(MODULE_NAME_error_page_inherit)

# error-page-inherit

MODULE_VERSION_PREFIX_error_page_inherit=$(BASE_VERSION)+

define MODULE_POST_error_page_inherit
cat <<BANNER
----------------------------------------------------------------------

The $(MODULE_SUMMARY_error_page_inherit) for $(MODULE_SUMMARY_PREFIX) have been installed.
To enable these modules, add the following to /etc/nginx/nginx.conf
and reload nginx:

    load_module modules/$(MODULE_NAME_error_page_inherit).so;

----------------------------------------------------------------------
BANNER
endef
export MODULE_POST_error_page_inherit
