MODULES+=	markdown-filter

MODULE_SUMMARY_markdown_filter=		Dynamic module markdown filter for nginx

MODULE_CONTRIB_DEPS_markdown-filter=	ngx_markdown_filter_module

include $(foreach dep,$(MODULE_CONTRIB_DEPS_markdown-filter),$(CONTRIB)/src/$(dep)/version)

NAME_markdown_filter=		ngx_markdown_filter_module

MODULE_VERSION_markdown_filter=		0.1.7
MODULE_RELEASE_markdown_filter=		1

MODULE_VERSION_PREFIX_markdown_filter=	$(MODULE_TARGET_PREFIX)

MODULE_PACKAGE_VENDOR_markdown_filter=		Karim Ulzhabayev <nginx-packaging@f5.com>

MODULE_PACKAGE_URL_markdown_filter=		https://github.com/ukarim

MODULE_PACKAGE_LICENSE_markdown_filter=	MIT

MODULE_SOURCES_markdown_filter=		ngx_markdown_filter_module-$(NGX_MARKDOWN_FILTER_MODULE_VERSION).tar.gz

MODULE_CONFARGS_markdown_filter=	--add-dynamic-module=$(MODSRC_PREFIX)$(NAME_markdown_filter)

# markdown-filter

MODULE_VERSION_PREFIX_markdown_filter=$(BASE_VERSION)+

MODULE_BUILD_DEPENDS_markdown_filter=,libcmark-dev

define MODULE_POST_markdown_filter
cat <<BANNER
----------------------------------------------------------------------

The $(MODULE_SUMMARY_markdown_filter) for nginx have been installed.
To enable this module, add the following to /etc/nginx/modules-enabled/module-markdown-filter.conf
and reload nginx:

    load_module modules/$(NAME_markdown_filter).so;

----------------------------------------------------------------------
BANNER
endef
export MODULE_POST_markdown_filter
