MODULES+=	markdown-filter

MODULE_SUMMARY_markdown_filter=		Dynamic module markdown filter for nginx

include $(CONTRIB)/src/ngx_markdown_filter_module/version

MODULE_VERSION_markdown_filter=		$(MARKDOWN_FILTER_NGINX_MODULE_VERSION)
MODULE_RELEASE_markdown_filter=		1

MODULE_VERSION_PREFIX_markdown_filter=	$(MODULE_TARGET_PREFIX)

MODULE_SOURCES_markdown_filter=		ngx_markdown_filter_module-$(MARKDOWN_FILTER_NGINX_MODULE_VERSION).tar.gz

MODULE_CONFARGS_markdown_filter=	--add-dynamic-module=ngx_markdown_filter_module-$(MARKDOWN_FILTER_NGINX_MODULE_VERSION)

.deps-module-markdown-filter:
	cd $(CONTRIB) && make .sum-ngx_markdown_filter_module
	touch $@

# markdown-filter

define MODULE_DEFINITIONS_markdown_filter
BuildRequires: cmark-devel
export MODULE_DEFINITIONS_markdown_filter
endef

define MODULE_POST_markdown_filter
cat <<BANNER
----------------------------------------------------------------------

The $(MODULE_SUMMARY_markdown) for nginx have been installed.
To enable this module, add the following to /etc/nginx/modules-enabled/module-markdown-filter.conf
and reload nginx:

    load_module modules/ngx_markdown_filter_module.so;

----------------------------------------------------------------------
BANNER
endef
export MODULE_POST_markdown_filter
