MODULES+=	include-server

MODULE_SUMMARY_include_server=	enable support to include_server derective in nginx.conf.

NAME_include_server=		ngx_http_include_server_module

MODULE_CONTRIB_DEPS_include_server=	$(NAME_include_server)

include $(foreach dep,$(MODULE_CONTRIB_DEPS_include_server),$(CONTRIB)/src/$(dep)/version)

MODULE_VERSION_include_server=	$(NGX_HTTP_INCLUDE_SERVER_MODULE_VERSION)
MODULE_RELEASE_include_server=	1

MODULE_VERSION_PREFIX_include_server=$(MODULE_TARGET_PREFIX)

MODULE_PACKAGE_VENDOR_include_server=		Georgy Shelkovy [RekGRpth]

MODULE_PACKAGE_URL_include_server=		https://github.com/RekGRpth

MODULE_NAME_include_server=	$(NAME_include_server)

MODULE_PACKAGE_LICENSE_include_server=	MIT

MODULE_SOURCES_include_server=	$(GITHUB)/$(MODULE_NAME_include_server).git

MODULE_CONFARGS_include_server=	--add-dynamic-module=$(MODULE_NAME_include_server)

# include-server

MODULE_VERSION_PREFIX_include_server=$(BASE_VERSION)+

define MODULE_POST_include_server
cat <<BANNER
----------------------------------------------------------------------

The $(MODULE_SUMMARY_include_server) for $(MODULE_SUMMARY_PREFIX) have been installed.
To enable these modules, add the following to /etc/nginx/nginx.conf
and reload nginx:

    load_module modules/$(MODULE_NAME_include_server).so;

----------------------------------------------------------------------
BANNER
endef
export MODULE_POST_include_server
