MODULES+=	error-page-inherit

MODULE_SUMMARY_error_page_inherit=	enable support to error_page_inherit derective in nginx.conf.

include $(CONTRIB)/src/ngx_http_error_page_inherit_module/version

MODULE_VERSION_error_page_inherit=	$(ERROR_PAGE_INHERIT_NGINX_MODULE_VERSION)
MODULE_RELEASE_error_page_inherit=	1

MODULE_VERSION_PREFIX_error_page_inherit=$(MODULE_TARGET_PREFIX)

MODULE_SOURCES_error_page_inherit=	ngx_http_error_page_inherit_module-$(ERROR_PAGE_INHERIT_NGINX_MODULE_VERSION).tar.gz

MODULE_CONFARGS_error_page_inherit=	--add-dynamic-module=ngx_http_error_page_inherit_module-$(ERROR_PAGE_INHERIT_NGINX_MODULE_VERSION)

.deps-module-error-page-inherit:
	cd $(CONTRIB) && make .sum-ngx_http_error_page_inherit_module
	touch $@

#define MODULE_DEFINITIONS_error_page_inherit
#BuildRequires: libmaxminddb-devel
#endef
#export MODULE_DEFINITIONS_error_page_inherit

define MODULE_POST_error_page_inherit
cat <<BANNER
----------------------------------------------------------------------

The $(MODULE_SUMMARY_error_page_inherit) for $(MODULE_SUMMARY_PREFIX) have been installed.
To enable these modules, add the following to /etc/nginx/nginx.conf
and reload nginx:

    load_module modules/ngx_http_error_page_inherit_module.so;

----------------------------------------------------------------------
BANNER
endef
export MODULE_POST_error_page_inherit
